"""
Bug Report Generator Service - Creates formatted bug reports from detected issues
"""
from datetime import datetime
from typing import Dict, List, Optional
import json


class BugReportGenerator:
    """
    Generates bug reports from detected issues with pre-filled templates.
    Supports multiple export formats: JSON, Markdown, Jira, GitHub Issues.
    """

    # Templates for different bug tracking systems
    TEMPLATES = {
        'default': {
            'title': '{severity}: {title}',
            'description': '''## Description
{description}

## Environment
- Device: {device_model}
- Firmware: {firmware_version}
- Serial: {serial_number}

## Error Details
- Category: {category}
- First Seen: {first_occurrence}
- Last Seen: {last_occurrence}
- Occurrence Count: {occurrence_count}

## Log Excerpt
```
{log_context}
```

## Affected Lines
{affected_lines}

## Steps to Reproduce
1. [Describe the actions that led to this issue]
2. [Include any relevant test steps]
3. [Note any specific conditions]

## Expected Behavior
[Describe what should have happened]

## Actual Behavior
{description}

## Additional Notes
Confidence Score: {confidence_score}%
''',
        },

        'jira': {
            'title': '[{severity}] {title}',
            'description': '''h2. Description
{description}

h2. Environment
* *Device:* {device_model}
* *Firmware:* {firmware_version}
* *Serial:* {serial_number}

h2. Error Details
||Property||Value||
|Category|{category}|
|First Seen|{first_occurrence}|
|Last Seen|{last_occurrence}|
|Occurrences|{occurrence_count}|

h2. Log Excerpt
{{code}}
{log_context}
{{code}}

h2. Affected Lines
{affected_lines}

h2. Steps to Reproduce
# [Describe the actions that led to this issue]
# [Include any relevant test steps]
# [Note any specific conditions]

h2. Expected Behavior
[Describe what should have happened]

h2. Actual Behavior
{description}

h2. Additional Notes
_Confidence Score: {confidence_score}%_
_Auto-generated by Sentinel Logger_
''',
        },

        'github': {
            'title': '{title}',
            'description': '''### Description
{description}

### Environment
| Property | Value |
|----------|-------|
| Device | {device_model} |
| Firmware | {firmware_version} |
| Serial | {serial_number} |

### Error Details
- **Category:** {category}
- **Severity:** {severity}
- **First Seen:** {first_occurrence}
- **Last Seen:** {last_occurrence}
- **Occurrences:** {occurrence_count}

### Log Excerpt
```
{log_context}
```

### Affected Lines
{affected_lines}

### Steps to Reproduce
1. [ ] Step 1
2. [ ] Step 2
3. [ ] Step 3

### Expected Behavior
[Describe what should have happened]

### Actual Behavior
{description}

---
<sub>Confidence Score: {confidence_score}% | Auto-generated by Sentinel Logger</sub>
''',
        },

        'minimal': {
            'title': '{title}',
            'description': '''{description}

Category: {category}
Severity: {severity}
Occurrences: {occurrence_count}
Time Range: {first_occurrence} - {last_occurrence}

Log Context:
{log_context}
''',
        }
    }

    def __init__(self):
        pass

    def generate_report(
        self,
        issue: Dict,
        device_info: Optional[Dict] = None,
        template_name: str = 'default',
        additional_context: Optional[str] = None
    ) -> Dict:
        """
        Generate a bug report from an issue.

        Args:
            issue: Issue dictionary with details
            device_info: Optional device/camera metadata
            template_name: Template to use (default, jira, github, minimal)
            additional_context: Extra context to append

        Returns:
            Dictionary with formatted bug report
        """
        template = self.TEMPLATES.get(template_name, self.TEMPLATES['default'])

        # Prepare device info
        device = device_info or {}
        device_model = device.get('model', 'Unknown')
        firmware_version = device.get('firmware_version', 'Unknown')
        serial_number = device.get('serial_number', 'Unknown')

        # Format affected lines
        affected_lines = issue.get('affected_lines', [])
        if isinstance(affected_lines, str):
            try:
                affected_lines = json.loads(affected_lines)
            except (json.JSONDecodeError, ValueError):
                affected_lines = []

        if len(affected_lines) > 10:
            lines_str = f"Lines {affected_lines[0]}-{affected_lines[-1]} ({len(affected_lines)} total)"
        else:
            lines_str = ', '.join(map(str, affected_lines)) if affected_lines else 'N/A'

        # Format timestamps
        first_occ = issue.get('first_occurrence')
        last_occ = issue.get('last_occurrence')
        if isinstance(first_occ, datetime):
            first_occ = first_occ.strftime('%Y-%m-%d %H:%M:%S')
        if isinstance(last_occ, datetime):
            last_occ = last_occ.strftime('%Y-%m-%d %H:%M:%S')

        # Prepare template variables
        variables = {
            'title': issue.get('title', 'Issue Detected'),
            'description': issue.get('description', 'No description available'),
            'severity': issue.get('severity', 'UNKNOWN'),
            'category': issue.get('category', 'general'),
            'first_occurrence': first_occ or 'Unknown',
            'last_occurrence': last_occ or 'Unknown',
            'occurrence_count': issue.get('occurrence_count', 1),
            'log_context': issue.get('context', 'No log context available'),
            'affected_lines': lines_str,
            'confidence_score': int(issue.get('confidence_score', 0) * 100),
            'device_model': device_model,
            'firmware_version': firmware_version,
            'serial_number': serial_number,
        }

        # Generate formatted content
        title = template['title'].format(**variables)
        description = template['description'].format(**variables)

        if additional_context:
            description += f"\n\n## Additional Context\n{additional_context}"

        return {
            'title': title,
            'description': description,
            'severity': issue.get('severity'),
            'category': issue.get('category'),
            'steps_to_reproduce': '',  # To be filled by user
            'expected_behavior': '',  # To be filled by user
            'actual_behavior': issue.get('description'),
            'environment': json.dumps(device or {}),
            'log_snippets': issue.get('context', ''),
            'template_used': template_name,
            'created_at': datetime.utcnow().isoformat()
        }

    def export_to_json(self, report: Dict) -> str:
        """Export report as JSON string"""
        return json.dumps(report, indent=2, default=str)

    def export_to_markdown(self, report: Dict) -> str:
        """Export report as Markdown"""
        return report.get('description', '')

    def export_to_text(self, report: Dict) -> str:
        """Export report as plain text"""
        text = f"""
BUG REPORT
==========

Title: {report.get('title', 'N/A')}
Severity: {report.get('severity', 'N/A')}
Category: {report.get('category', 'N/A')}
Created: {report.get('created_at', 'N/A')}

DESCRIPTION
-----------
{report.get('description', 'N/A')}

LOG SNIPPETS
------------
{report.get('log_snippets', 'N/A')}
"""
        return text.strip()

    def generate_summary_report(self, issues: List[Dict], log_file_info: Dict) -> str:
        """
        Generate a summary report for multiple issues.

        Args:
            issues: List of issue dictionaries
            log_file_info: Information about the analyzed log file

        Returns:
            Formatted summary report as string
        """
        # Count by severity
        severity_counts = {}
        for issue in issues:
            sev = issue.get('severity', 'UNKNOWN')
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        # Count by category
        category_counts = {}
        for issue in issues:
            cat = issue.get('category', 'unknown')
            category_counts[cat] = category_counts.get(cat, 0) + 1

        report = f"""
# Log Analysis Summary Report

Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

## File Information
- Filename: {log_file_info.get('filename', 'Unknown')}
- Total Lines: {log_file_info.get('total_lines', 0):,}
- Errors: {log_file_info.get('error_count', 0):,}
- Warnings: {log_file_info.get('warning_count', 0):,}

## Issues Summary
- Total Issues Detected: {len(issues)}

### By Severity
"""
        for sev in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
            count = severity_counts.get(sev, 0)
            if count > 0:
                report += f"- {sev}: {count}\n"

        report += "\n### By Category\n"
        for cat, count in sorted(category_counts.items(), key=lambda x: -x[1]):
            report += f"- {cat}: {count}\n"

        if issues:
            report += "\n## Critical and High Severity Issues\n"
            for i, issue in enumerate(issues[:10], 1):
                if issue.get('severity') in ['CRITICAL', 'HIGH']:
                    report += f"""
### {i}. {issue.get('title')}
- Severity: {issue.get('severity')}
- Category: {issue.get('category')}
- Occurrences: {issue.get('occurrence_count', 1)}
- Description: {issue.get('description', 'N/A')[:200]}
"""

        report += """
---
*Generated by Sentinel Logger*
"""
        return report.strip()
